### ISSUE TITLE
AndroidDeviceFinder only recognizing Motorola devices 

### ISSUE THREAD

**Issue by diegorq** [Testinium/MobileDeviceInfo#7]
I've been using this class for a while in a Motorola device that I own. When I needed to run some tests with another device (Samsung or xiaomi) the error. I tried others motorola devices and they work fine. If I remove the use of MobileDeviceInfo methos, the devices works fine too. Is there any aditional configuration that I need to do for those devices?

`java.lang.ArrayIndexOutOfBoundsException: 1
    at com.testinium.deviceinformation.device.AndroidDeviceFinder.readDeviceInfo(AndroidDeviceFinder.java:60)
    at com.testinium.deviceinformation.device.AndroidDeviceFinder.findDevices(AndroidDeviceFinder.java:26)
    at com.testinium.deviceinformation.device.DeviceFinder.findDevices(DeviceFinder.java:14)
    at com.testinium.deviceinformation.DeviceInfoImpl.getDevices(DeviceInfoImpl.java:36)
    at com.testinium.deviceinformation.DeviceInfo.getFirstDevice(DeviceInfo.java:16)
    at core.MobileDriverFactory.setAndroidCapabilities(MobileDriverFactory.java:65)`

**Comment by bahadirustun** [comment]
There is no configuration, the Prerequisites found in ReadMe.md must fulfill.
version has been updated, you can try again with the new version.
